file:
  pattern: "*.xml"
  
local:
  workingdir: "/Users/aacevedo/Documents/development/sources/tmp/"
  input-stream: "in-stream/"
  input-mimetype: "in-mimetype/"
  output: "out/"
  reconnection.frequency: "2500"
  reconnection.attempts: "2"  